pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
	stage('Manual Approval'){
	steps{
	input message: 'Lanjutkan ke tahap Deploy?,' ok: 'Proceed'	
	    }
	}
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                echo 'Application is running. Waiting for 1 minute...'
		sleep 60
		echo '1 minute elapsed. Stopping application...'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
